config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    collection do
      get "top", to: "restaurants#top"
    end
    member do
      get "chef", to: "restaurants#chef"
    end
    resources :reviews, only: [:new, :create, :destroy]
  end

  namespace :admin do
    resources :restaurants, only: [:index]
  end

  root to: 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :user

  validates :name, presence: true, uniqueness: true
  validates :city, presence: true
  validates :food_type, presence: true
  validates :rating, presence: true, inclusion: { in: [1,2,3,4,5], allow_nil: false}

  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?

  mount_uploader :photo, PhotoUploader
  mount_uploader :photo_of_the_chef, PhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :restaurants
  has_many :reviews, through: :restaurants
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: [:index, :top, :show], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :top, :show], unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError,   with: :user_not_authorized
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # def configure_permitted_parameters
  #   update_attrs = [:password, :password_confirmation, :current_password]
  #   devise_parameter_sanitizer.permit :account_update, keys: update_attrs
  # end

  private

  def skip_pundit?
    devise_controller?
  end

  def user_not_authorized(exception)
    render json: {
      error: "Sorry, you are not authorized to perform that action."
    }, status: :unauthorized
  end

  def default_url_options
  { host: ENV["HOST"] || "localhost:3000" }
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :chef]
  skip_before_action :authenticate_user!, only: [:index, :show, :top]

  def chef
  end

  def top
    @top_restaurants = policy_scope(Restaurant.where(rating: 5))
  end

  def index
    @restaurants = policy_scope(Restaurant)
    @restaurants = Restaurant.where.not(latitude: nil, longitude: nil)

    @markers = @restaurants.map do |restaurant|
      {
        lng: restaurant.longitude,
        lat: restaurant.latitude
      }
    end
  end

  def show
    @restaurants = policy_scope(Restaurant)
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    authorize @restaurant

    if @restaurant.save
      redirect_to restaurants_path, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :city, :food_type, :rating, :photo, :chef, :photo_of_the_chef, :photo_cache, :photo_of_the_chef_cache)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = Review.new
    authorize @restaurant
    authorize @review
  end
  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.restaurant = @restaurant
    authorize @restaurant
    authorize @review

    if @review.save
      redirect_to restaurant_path(@restaurant), notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def destroy
    set_review
    @reviews.destroy
    redirect_to restaurants_url, notice: 'Review was successfully destroyed.'
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    authorize @restaurant
  end

  def set_review
    @reviews = @restaurant.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/restaurants/index.html.erb
<h1>My Restaurants</h1>

<%= link_to "Add a restaurant", new_restaurant_path %>

<% @restaurants.each do |restaurant| %>
  <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
  <p><%= restaurant.city %></p>
  <p><%= restaurant.food_type %></p>
  <p><%= "*" * restaurant.rating %></p>
  <p> <%= link_to "Remove restaurant", restaurant_path(restaurant), method: :delete %></p>
  <p> <%= link_to "See the Chef", chef_restaurant_path(restaurant) %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Restaurant Advisor" %></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/restaurants/_card.html.erb
<% if restaurant.photo.present? %>
  <div class="card card_margin" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path restaurant.photo, height: 300, width: 400, crop: :fill %>')">
  <div>
<% else %>
  <div class="card card_margin" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path "nophoto.png" %>')">
  <div>
<% end %>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant), class:"link-style" %></h2>
    <p>City: <%= restaurant.city %></p>
    <p>Food Type: <%= restaurant.food_type %></p>
    <p>Rating: (<span class="star"><%= "*" * restaurant.rating %></span>)</p>
  </div>
</div>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.error_notification %>

  <div>
    <%= f.input :name %>
    <%= f.input :city %>
    <%= f.input :food_type, label: "Type of food" %>
    <%= f.input :rating, collection: 1..5, prompt: "Number of stars"%>
    <p>Add a photo of the restaurant here</p>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <p>Add the chef of the restaurant here</p>
    <%= f.input :chef %>
    <p>Add a photo of the chef of the restaurant here</p>
    <%= f.input :photo_of_the_chef %>
    <%= f.input :photo_of_the_chef_cache, as: :hidden %>
  </div>

  <div>
    <%= f.button :submit, class: "button yellow-button" %>
  </div>
<% end %>

app/views/restaurants/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="See-the-chef" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1 class="modal-title" id="myModalLabel">Chef of <%= @restaurant.name %></h1>
      </div>

      <div class="modal-body">
        <h2><%= @restaurant.chef %></h2>
        <% if @restaurant.photo_of_the_chef.present? %>
        <div class="avatar" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @restaurant.photo_of_the_chef, height: 250, width: 250, crop: :thumb, gravity: :face %>')">
        </div>
      <% else %>
        <div class="card card_margin" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path "nophoto.png" %>')">
        </div>
      <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="button yellow-button" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
<div class="container layout bottom-padding">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-3">
      <h1 class="page-padding">Edit Restaurant</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="home-layout">
  <div class="background">
    <h1 class="all-restaurants">All Restaurants</h1>
    <div class="typed-padding">
      <h2 class="all-restaurants">Restaurant Advisor. <span id="banner-typed-text"></span></h2>
    </div>
    <div>
    <% @restaurants.each do |r| %>
      <div class="col-xs-10 col-md-6">
        <%= render "card", restaurant: r %>
      </div>
    <% end %>
    </div>
  </div>
  <div
    id="map"
    style="width: 95%;
    height: calc(100vh - 80px);"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/restaurants/new.html.erb
<div class="container layout bottom-padding">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-3">
      <h1 class="page-padding">Add a Restaurant</h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<% content_for(:title) do %>
  <%= @restaurant.name %> is on Restauant Advisor
<% end %>

<div class="container layout">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-3">
      <h1 class="page-padding"><%= @restaurant.name %></h1>
      <% if @restaurant.photo.present? %>
        <div class="large_card card_bottom_margin" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path @restaurant.photo, height: 300, width: 400, crop: :fill %>')">
        </div>
      <% else %>
        <div class="card card_bottom_margin" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path "nophoto.png" %>')">
        </div>
      <% end %>
      <p>City: <%= @restaurant.city %></p>
      <p>Food Type: <%= @restaurant.food_type %></p>
      <p>Rating: (<span class="star"><%= "*" * @restaurant.rating %></span>)</p>

      <p>Reviews:</p>
      <% if @restaurant.reviews.none? %>
        <ul>
          <li>Be the first to review this restaurant!</li>
        </ul>
      <% else %>
        <ul>
          <% @restaurant.reviews.each do |review| %>
            <li><%= review.content %></li>
          <% end %>
        </ul>
      <% end %>

      <p><%= link_to "Add review", new_restaurant_review_path(@restaurant), class: 'button yellow-button' %></p>
      <p><button type="button" class="button yellow-button" data-toggle="modal" data-target="#See-the-chef">See the Chef</button><%= render "modal" %></p>
      <% if policy(@restaurant).edit? %>
        <p><%= link_to 'Edit', edit_restaurant_path(@restaurant), class: 'button yellow-button' %></p>
        <p><%= link_to "Remove restaurant", @restaurant, method: :delete, data: {confirm: 'Are you sure?' }, class: 'button yellow-button'%></p>
      <% end %>
      <div>
      <p><%= link_to "Back to all restaurants", restaurants_path, class: 'button yellow-button top-margin' %></p>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/top.html.erb
<div class="container layout">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-3">
      <h1 class="page-padding">Our best restaurants</h1>
      <ul>
        <% @top_restaurants.each do |restaurant| %>
          <li>
            <p><%= restaurant.name %> (<span class="star"><%= "*" * restaurant.rating %></span>)</p>
            <% if restaurant.photo.present? %>
              <div class="small-card card_bottom_margin" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path restaurant.photo %>')">
              </div>
            <% else %>
              <div class="small-card card_bottom_margin" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path "nophoto.png" %>')">
              </div>
            <% end %>
            <p>City: <%= restaurant.city %></p>
            <p>Food Type: <%= restaurant.food_type %></p>
            <p><%= link_to 'More Info', restaurant_path(restaurant), class: 'button yellow-button' %></p>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container layout">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-3">
      <h1 class="page-padding">Post review for <%= @restaurant.name %></h1>
      <%= simple_form_for [@restaurant, @review] do |f| %>
        <%= f.input :content, placeholder: "Great food" %>
        <%= f.submit "Add review", class: "button yellow-button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible login_logout_notice_space" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible login_logout_notice_space" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <a href="#"><i class="fab fa-instagram footer-padding"></i></a>
  <a href="#"><i class="fab fa-facebook footer-padding"></i></a>
  <a href="#"><i class="fab fa-twitter footer-padding"></i></a>
  <a href="#"><i class="fab fa-linkedin footer-padding"></i></a>
</div>

app/views/shared/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="icon-bar top-bar"></span>
        <span class="icon-bar middle-bar"></span>
        <span class="icon-bar bottom-bar"></span>
      </button>
      <div class="home"> <%= link_to "", root_path, class:"fas fa-home fa-2x home-logo"%></div>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Top Restaurants", top_restaurants_path %></li>
        <li><%= link_to "Add a restaurant", new_restaurant_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Edit Account", edit_user_registration_path %></li>
            <li><%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          <% else %>
            <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path %></li>
          <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</nav>